apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-chart.fullname" . }}
  labels:
    {{- include "flask-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}  # Service type (ClusterIP or LoadBalancer)
  ports:
    - port: {{ .Values.service.port }}  # Service port (exposed port)
      targetPort: 5000                 # Target port in the container (Flask app)
      protocol: TCP
      name: http
  selector:
    {{- include "flask-app-chart.selectorLabels" . | nindent 4 }}  # Match labels for pod selection
